name: Build and publish package

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Install pnpm
              uses: pnpm/action-setup@v6
              with:
                  version: 11
            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24.4.0
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@oudshoorn-hydraulics'
            - run: pnpm install
            - run: pnpm lint
            - run: pnpm build
            - run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
